[package]
name = "miniprot"
version = "0.1.0"
edition = "2024"

[lib]
name = "miniprot"
path = "src/lib.rs"

[[bin]]
name = "miniprot"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.0", features = ["derive"] }
niffler = { version = "3.0.0", default-features = false, features = ["gz"] }
noodles = { version = "0.109.0", features = ["core", "fasta", "gff", "gtf", "sam"] }
rayon = "1.11.0"
zerocopy = { version = "0.8.48", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.2.0"
flate2 = { version = "1.1.9", default-features = false, features = ["zlib-rs"] }
tempfile = "3.27.0"
